-- AlterTable
ALTER TABLE "Sheet" ALTER COLUMN "MST1_Q1" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "MST1_Q2" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "MST1_Q3" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "MST2_Q1" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "MST2_Q2" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "MST2_Q3" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "EndSem_Q1" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "EndSem_Q2" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "EndSem_Q3" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "EndSem_Q4" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "EndSem_Q5" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "Assignment_CO1" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "Assignment_CO2" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "Assignment_CO3" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "Assignment_CO4" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "Assignment_CO5" SET DATA TYPE DECIMAL(65,30);

-- CreateTable
CREATE TABLE "Levels" (
    "subjectCode" TEXT NOT NULL,
    "CO1" DECIMAL(65,30),
    "CO2" DECIMAL(65,30),
    "CO3" DECIMAL(65,30),
    "CO4" DECIMAL(65,30),
    "CO5" DECIMAL(65,30),

    CONSTRAINT "Levels_pkey" PRIMARY KEY ("subjectCode")
);

-- AddForeignKey
ALTER TABLE "Levels" ADD CONSTRAINT "Levels_subjectCode_fkey" FOREIGN KEY ("subjectCode") REFERENCES "Subject"("code") ON DELETE RESTRICT ON UPDATE CASCADE;
