-- AlterTable
ALTER TABLE "Sheet" ADD COLUMN     "Indirect_CO1" DECIMAL(65,30),
ADD COLUMN     "Indirect_CO2" DECIMAL(65,30),
ADD COLUMN     "Indirect_CO3" DECIMAL(65,30),
ADD COLUMN     "Indirect_CO4" DECIMAL(65,30),
ADD COLUMN     "Indirect_CO5" DECIMAL(65,30);
